### ISSUE TITLE
Drop `promise` lib?

### ISSUE THREAD

**Issue by L-as** [o1-labs/snarkyjs-bindings#111]
You don't need it.
A thread pool is needed anyway, you can run the async_kernel scheduler in there too.
You can await on a Deferred.t by using the Promise constructor and calling the `resolve` function passed in from within the Ivar's handler.
You can implement `from_deferred : 'a Deferred.t -> a Promise.t` too using this simple trick,
but I'm not sure the library has any point at that point. All you really want is the `to_js` and `of_js` functions.

**Comment by mitschabaude** [comment]
Hey this is interesting!

>  A thread pool is needed anyway, you can run the async_kernel scheduler in there too.
You can await on a Deferred.t by using the Promise constructor and calling the resolve function passed in from within the Ivar's handler.

I'm not sure I understand what you're suggesting. "Running the async_kernel scheduler" sounds heavy.. is this something that runs the whole time in a blocking way? (If yes, wouldn't be usable for a web library). Note that by using promises, which use the JavaScript event loop, which is a "scheduler" native to the runtime.

**Comment by mitschabaude** [comment]
> You can await on a Deferred.t by using the Promise constructor and calling the resolve function passed in from within the Ivar's handler.

Yeah I think the point of creating the Promise library back then was that these Deferreds never resolved because there was no scheduler. So I guess the point was to implement `run_in_thread` in a way that works for JS

**Comment by mitschabaude** [comment]
> You can implement from_deferred : 'a Deferred.t -> a Promise.t too using this simple trick

Yeah looks like I had this implemented, but removed it because Deferred.t would never resolve anyway:
https://github.com/MinaProtocol/mina/commit/9b50b3dee45478658bbc4ca0b93b3cf8f1fcee31

**Comment by mitschabaude** [comment]
@L-as ok cool! sounds like you found a reasonable solution. In snarkyjs, I still prefer to keep native JS promises over a userland implementation compiled from ocaml, as long as we don't need `async_kernel`

Closing for now!
