### ISSUE TITLE
Having trouble regenerating

### ISSUE THREAD

**Issue by L-as** [o1-labs/snarkyjs-bindings#28]
.

**Comment by L-as** [comment]
I'm dumb, of course, I had a change, I was including core by accident.

**Comment by L-as** [comment]
I get another error however:
`Error: execve(./dump-test-vectors.sh): No such file or directory`

This isn't quite clear to me. The file is there, why is the CWD not what it's supposed to be?

**Comment by mitschabaude** [comment]
No idea, I probably need more context to help. I run these scripts all the time and they also run in Mina CI

**Comment by L-as** [comment]
Closed by #29
