### ISSUE TITLE
`npm run make` broken on `berkeley`

### ISSUE THREAD

**Issue by L-as** [o1-labs/snarkyjs-bindings#66]
It doesn't put the compiled OCaml output in the `dist` directory

**Comment by L-as** [comment]
Or is `dist` not meant to be used anymore?

**Comment by mitschabaude** [comment]
No it's meant to be used. I'm surprised that you say it's not working

**Comment by mitschabaude** [comment]
Ah so its location inside `dist` changed. But I just checked that when running `npm run make`, it gets put here: `dist/node/bindings/compiled/_node_bindings`

**Comment by L-as** [comment]
The snarky.js file doesn't import in correctly anymore

**Comment by mitschabaude** [comment]
Hey @L-as could you give more details about what you think its not correct? It works fine in snarkyjs
